### ISSUE TITLE
Fixing faces, does this fix black face issues due to conflicting mods?

### ISSUE THREAD

**Issue by kevdevrev** [Synthesis-Collective/facefixer#5]

**Comment by tr4wzified** [comment]
If you configure it correctly, yes. Make sure the mod order in MO2 is the same as in the FaceFixer settings and it'll take care of it.

**Comment by kevdevrev** [comment]
Awesome thanks! This is a great tool to have since the "face discoloration fix" mod does not work on VR due to address library. Thanks a bunch!

**Comment by kevdevrev** [comment]
Question, do I have to manually input my MO2 load order to the Target mods section? Or is it supposed to do it automatically?

**Comment by theSkyseS** [comment]
You need to put only your npc appearance mods into facefixer

**Comment by tr4wzified** [comment]
Adding to that, Face Discoloration Fix just removes the 'stand out' black face the devs put in so that their testers would immediately notice broken NPC visuals. The meshes/color still won't match up perfectly, it just puts a bandaid on there. You need to let the meshes from the mods you want to see in-game win over the other mods in MO2 (left pane) and then add their plugins into the FaceFixer.
